import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Next",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    // <html lang="en" data-theme="light" >
    <html lang="en">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
    >
    <Navbar/>
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  );
}
